### ISSUE TITLE
site rendering on deploy

### ISSUE THREAD

**Issue by questoph** [kdevo/osprey-delight#29]
hi there,
i'm running into some trouble with the rendering of a site built with your theme. locally, everything runs smoothly, upon upload to the web server, however, the site does seem to miss images, links and css rendering. i've cross-checked with some other hugo-based sites in the same public directory, all of which work nicely. so it must be something in (what i've done with) the theme.

i've slightly adapted a couple of partials (after copying them to my working directory) and scss files (also copied to my hugo working directory), so the theme basis should be intact & the altered files in the parent folders should replace the theme originals. also the overall site structure structure is identical with the template provided. I have both the newest version of hugo and osprey-delight installed.

solved already: was an issue with the reverse proxy of the company server. sry. :)

**Comment by kdevo** [comment]
Alright, good to hear that. Can this be closed? 

As a side note, with regard to the adaptions you've mentioned: Using the theme as a submodule and only making the changes directly in your site's directory is the preferred way for v4 (which from what I've understood you already did). I will release v5 in the next months, where most of the visuals stay the same. Many things under the hood will be changed though and due to a shift to Hugo modules the theme can easily be installed and updated via a simple `hugo mod get`. A not yet documented preview is available in the [dev](https://github.com/kdevo/osprey-delight/tree/dev) branch.

**Comment by questoph** [comment]
yup, let us close it. generally, when I build a new hugo site, I leave the theme intact and copy all resource I want to tamper with into the top level equivalent. hope I'll be fine as to v5 then :).
thanks for your work!
