### ISSUE TITLE
Syntax error in termynal.js

### ISSUE THREAD

**Issue by blutack** [kdevo/osprey-delight#7]
Hi kdevo,

Thanks for the great theme.

I found a problem when trying it out with broken layout which I tracked it down to the following construct in termynal.js.

`this.startDelay = options.startdelay || {{ .Site.Data.terminal.startDelay }};`

The templates aren't properly escaped if there is no termynal json configuration present, so the generated bundle includes lines like the following:
 
`this.startDelay = options.startdelay || <no value>;`

This isn't valid JS so all the JS powered features (including the nice sticky header, which was the first thing I noticed) break. 

As the options seem to be passed through the constructor anyway if the JSON config is available, possibly it would make sense to fall back on static values in this case (i.e. `this.startDelay = options.startdelay || 1000;`)? Otherwise, might be worth adding  documentation to clarify that useTermynal cannot be set true without a valid json config file.

I haven't provided a complete pull request as I'm not sure how/if you want to handle this? 
My 'fix' was just to disable useTermynal.

**Comment by kdevo** [comment]
Hi @blutack 

glad to see your detailed issue descriptions!
I'll have a look at it, attempt to reproduce the described bahavior and fix it accordingly.

Expect to see some updates within the `dev` branch this week! I am currently working on other features too, so your reports arrived at the right time. Stay tuned :rocket: 

Since it seems like you performed a whole migration to Osprey Delight, would you mind to list the most important steps for documentation? I am thinking about a document `MIGRATION.md` where I can put these points to assist former Osprey users (you can of course also create a PR with this file)

**Comment by blutack** [comment]
No problem! Unfortunately, I can't be too useful for migrating as the reason for the migration was that I'd lost the hugo sources to generate the site and just had the generated version (it's a very simple landing page type thing that never needs updating). However I recently decided it would be nice to start blogging, hence needed to set the hugo and CI stuff up properly.

It actually took me a while to figure out which theme I'd previously used, but as there was no blog stuff it was just a case of copying the about stuff and logo across and setting up config.md.

That single CSS issue was the only negative difference against the original site. Otherwise, the new logo on scroll etc stuff looks fantastic. I'm currently in the process of sorting out the blogging workflow, adding shortcodes (especially around images) and a floating side table of contents. My repo is https://github.com/Fluxense/osprey-delight but once I've got a solid blogging setup I'll happily create merge requests for the individual features.

**Comment by kdevo** [comment]
Cool that you like it!
Would be nice if you can provide merge requests for the blog stuff you're working on once they're finished.

There are still some styling issues that need to be improved for the blog that I didn't find the time for - I guess it's a never ending story, so I'm excited for any contribution!

---

**Regarding this issue:** I fixed it by always providing a `data/terminal.json` functioning as defaults within the theme's directory which can easily be overridden by the user within the data directory. I could not fix this via constructor as you've suggested because each gallery item can provide different values for the attributes (gallery items `terminal` config overrides `terminal.json` defaults).
